find_package(LLVM REQUIRED CONFIG)
if(NOT LLVM_VERSION_MAJOR EQUAL 18)
    message(FATAL_ERROR "kernelc requires LLVM/Clang 18")
endif()
find_path(LUTILS_CLANG_INCLUDE_DIR clang/AST/ASTContext.h HINTS ${LLVM_INCLUDE_DIRS} REQUIRED)
find_library(LUTILS_CLANG_CPP_LIBRARY NAMES clang-cpp clang-cpp.so.18.1 libclang-cpp.so.18.1 HINTS ${LLVM_LIBRARY_DIRS} REQUIRED)
add_library(lutils_clang INTERFACE)
target_include_directories(lutils_clang SYSTEM INTERFACE ${LUTILS_CLANG_INCLUDE_DIR} ${LLVM_INCLUDE_DIRS})
target_link_libraries(lutils_clang INTERFACE ${LUTILS_CLANG_CPP_LIBRARY} LLVM)
add_executable(lutils-kernelc main.cpp)
add_executable(lutils::kernelc ALIAS lutils-kernelc)
target_compile_features(lutils-kernelc PRIVATE cxx_std_17)
target_link_libraries(lutils-kernelc PRIVATE lutils_clang)
set_target_properties(lutils-kernelc PROPERTIES CXX_EXTENSIONS OFF)
