add_executable(expected_example expected.cpp)
add_executable(image_regions_example image_regions.cpp)
target_link_libraries(image_regions_example PRIVATE lutils::image_memory lutils_development)
target_link_libraries(expected_example PRIVATE lutils::core lutils_development)
set_target_properties(expected_example PROPERTIES CXX_EXTENSIONS OFF)

add_executable(erasure_counter counter.cpp)
target_link_libraries(erasure_counter PRIVATE lutils::erasure lutils_development)
set_target_properties(erasure_counter PROPERTIES CXX_EXTENSIONS OFF)

if(LUTILS_BUILD_KERNELC)
    add_executable(image_compute image_compute.cpp)
    target_link_libraries(image_compute PRIVATE lutils::image_ops lutils::compute_cpu lutils_development)
    if(LUTILS_ENABLE_VULKAN)
        target_link_libraries(image_compute PRIVATE lutils::compute_vulkan)
        target_compile_definitions(image_compute PRIVATE LUTILS_EXAMPLE_VULKAN)
    endif()
endif()
if(LUTILS_BUILD_KERNELC)
    add_executable(pdf_compute pdf_compute.cpp)
    target_link_libraries(pdf_compute PRIVATE lutils_pdf_kernels lutils::compute_cpu lutils_development)
    if(LUTILS_ENABLE_VULKAN)
        target_link_libraries(pdf_compute PRIVATE lutils::compute_vulkan)
        target_compile_definitions(pdf_compute PRIVATE LUTILS_EXAMPLE_VULKAN)
    endif()
endif()
