file(MAKE_DIRECTORY "${WORK}")
set(input "${WORK}/kernel.cpp")
file(WRITE "${input}" "// This input must never be replaced by generated code.\n")
file(SHA256 "${input}" expected)
function(reject)
    execute_process(COMMAND "${TOOL}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(SHA256 "${input}" actual)
    if(status EQUAL 0 OR NOT err MATCHES "output would overwrite input" OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Input overwrite guard failed: ${out}\n${err}")
    endif()
endfunction()
reject("${input}" --entry=run --name=test "--output=${WORK}/kernel" -- -std=c++17)
file(REMOVE "${WORK}/alias.cpp")
file(CREATE_LINK "${input}" "${WORK}/alias.cpp" SYMBOLIC)
reject("${input}" --entry=run --name=test "--output=${WORK}/alias" -- -std=c++17)
reject(--embed "${input}" "${WORK}/alias.cpp" test)
