
# CMake puts global flags after target definitions on the compiler command line.
# Forward only macro flags, preserving that order without passing GCC options to Clang.
function(lutils_kernel_macro_flags output flags)
    separate_arguments(arguments NATIVE_COMMAND "${flags}")
    set(result)
    set(prefix)
    foreach(argument IN LISTS arguments)
        if(argument MATCHES "^-include|^-imacros|^-Wp,|^-Xpreprocessor|^-Xclang|^@|^-I|^-isystem|^-iquote|^-idirafter|^-nostdinc|^--sysroot|^-isysroot")
            message(FATAL_ERROR "Kernel preprocessing cannot forward ${argument}; use INCLUDE_DIRS and DEFINITIONS")
        endif()
        if(prefix)
            list(APPEND result "${prefix}${argument}")
            set(prefix)
        elseif(argument MATCHES "^-D$|^-U$")
            set(prefix "${argument}")
        elseif(argument MATCHES "^-D.|^-U.")
            list(APPEND result "${argument}")
        endif()
    endforeach()
    if(prefix)
        message(FATAL_ERROR "Missing argument after ${prefix} in C++ flags")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(lutils_check_kernel_profile target)
    set(pending "${target}")
    set(checked)
    while(pending)
        list(POP_FRONT pending dependency)
        if(NOT TARGET "${dependency}" OR dependency IN_LIST checked)
            continue()
        endif()
        list(APPEND checked "${dependency}")
        foreach(property IN ITEMS COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS
                COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES)
            get_target_property(values "${dependency}" "${property}")
            if(values MATCHES "COMPILE_LANGUAGE|COMPILE_LANG_AND_ID|COMPILE_ONLY")
                message(FATAL_ERROR "Kernel ${target}: language-dependent expressions in ${dependency}/${property} cannot be shared with kernelc")
            endif()
            if(property MATCHES "OPTIONS" AND values MATCHES "SHELL:|(^|;)(-D|-U)($|;)|-include|-imacros|-Wp,|-Xpreprocessor|-Xclang|(^|;)@|(^|;)-I|(^|;)-isystem|(^|;)-iquote|(^|;)-idirafter|-nostdinc|--sysroot|-isysroot")
                message(FATAL_ERROR "Kernel ${target}: unsupported preprocessing option in ${dependency}; use INCLUDE_DIRS and DEFINITIONS, or joined -Dname/-Uname")
            endif()
        endforeach()
        foreach(property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(dependencies "${dependency}" "${property}")
            foreach(child IN LISTS dependencies)
                if(TARGET "${child}")
                    list(APPEND pending "${child}")
                endif()
            endforeach()
        endforeach()
    endwhile()
endfunction()

function(_lutils_add_kernel_impl target kind)
    find_program(LUTILS_GLSLANG glslangValidator REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    find_program(LUTILS_SPIRV_VAL spirv-val REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    if(TARGET lutils::kernelc)
        set(kernelc lutils::kernelc)
    else()
        set(kernelc lutils-kernelc)
    endif()
    if(CMAKE_CONFIGURATION_TYPES)
        message(FATAL_ERROR "Kernel generation currently requires a single-configuration generator such as Ninja")
    endif()
    cmake_parse_arguments(K "OBJECT" "NAME;SOURCE;ENTRY;LOCAL_SIZE_X" "INCLUDE_DIRS;DEFINITIONS;DEPENDS" ${ARGN})
    if(K_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Missing kernel argument values: ${K_KEYWORDS_MISSING_VALUES}")
    endif()
    if(NOT K_NAME OR NOT K_SOURCE OR NOT K_ENTRY)
        message(FATAL_ERROR "lutils_add_kernel requires NAME SOURCE ENTRY")
    endif()
    if(kind STREQUAL "object" AND DEFINED K_LOCAL_SIZE_X)
        message(FATAL_ERROR "lutils_add_shader takes local_size from the C++ kernel declaration")
    endif()
    if(NOT DEFINED K_LOCAL_SIZE_X)
        set(K_LOCAL_SIZE_X 1)
    endif()
    if(NOT K_LOCAL_SIZE_X MATCHES "^[1-9][0-9]*$" OR K_LOCAL_SIZE_X GREATER 4294967295)
        message(FATAL_ERROR "LOCAL_SIZE_X must be a positive 32-bit integer")
    endif()
    get_filename_component(source "${K_SOURCE}" ABSOLUTE)
    if(TARGET lutils::compute_kernel)
        get_target_property(sdk_include lutils::compute_kernel LUTILS_SDK_INCLUDE_DIR)
    else()
        get_filename_component(sdk_include "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../compute/kernel/include" ABSOLUTE)
    endif()
    set(base "${CMAKE_CURRENT_BINARY_DIR}/generated/${K_NAME}")
    set(include_dirs)
    foreach(dir IN LISTS K_INCLUDE_DIRS)
        get_filename_component(absolute "${dir}" ABSOLUTE)
        list(APPEND include_dirs "${absolute}")
    endforeach()
    lutils_kernel_macro_flags(global_macros "${CMAKE_CXX_FLAGS}")
    set(configurations ${CMAKE_CONFIGURATION_TYPES} ${CMAKE_BUILD_TYPE})
    list(REMOVE_DUPLICATES configurations)
    foreach(config IN LISTS configurations)
        string(TOUPPER "${config}" upper_config)
        lutils_kernel_macro_flags(config_macros "${CMAKE_CXX_FLAGS_${upper_config}}")
        foreach(macro IN LISTS config_macros)
            list(APPEND global_macros "$<$<CONFIG:${config}>:${macro}>")
        endforeach()
    endforeach()
    set(definitions "$<TARGET_GENEX_EVAL:${target},$<TARGET_PROPERTY:${target},COMPILE_DEFINITIONS>>")
    set(includes "$<TARGET_GENEX_EVAL:${target},$<TARGET_PROPERTY:${target},INCLUDE_DIRECTORIES>>")
    set(options "$<TARGET_GENEX_EVAL:${target},$<TARGET_PROPERTY:${target},COMPILE_OPTIONS>>")
    set(target_profile)
    if(ANDROID)
        # kernelc runs on the host but parses the same target headers and builtins.
        list(APPEND target_profile "--target=${CMAKE_CXX_COMPILER_TARGET}"
            "--sysroot=${CMAKE_SYSROOT}" -stdlib=libc++
            "-isystem${CMAKE_SYSROOT}/usr/include/c++/v1")
    elseif(CMAKE_CROSSCOMPILING)
        message(FATAL_ERROR "Kernel preprocessing has no profile for this cross-compilation toolchain")
    endif()
    add_custom_command(OUTPUT "${base}.hpp" "${base}.cpp" "${base}.comp" "${base}.spv" "${base}.spv.hpp"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/generated"
        COMMAND "$<TARGET_FILE:${kernelc}>" "${source}" --entry=${K_ENTRY} --name=${K_NAME} --output=${base}
            --local-size-x=${K_LOCAL_SIZE_X} --expect-kind=${kind}
            -- -std=c++17 -Werror=macro-redefined ${target_profile} "-I${sdk_include}"
            "$<$<BOOL:${includes}>:-I$<JOIN:${includes},;-I>>"
            "$<$<BOOL:${definitions}>:-D$<JOIN:${definitions},;-D>>"
            ${global_macros} "$<FILTER:${options},INCLUDE,^-D.|^-U.>"
        COMMAND "${LUTILS_GLSLANG}" -V --target-env vulkan1.1 -o "${base}.spv" "${base}.comp"
        COMMAND "${LUTILS_SPIRV_VAL}" --target-env vulkan1.1 "${base}.spv"
        COMMAND "$<TARGET_FILE:${kernelc}>" --embed "${base}.spv" "${base}.spv.hpp" "${K_NAME}"
        DEPENDS ${kernelc} "${source}" "${sdk_include}/lutils/compute/Kernel.hpp" ${K_DEPENDS}
        DEPFILE "${base}.d"
        COMMAND_EXPAND_LISTS VERBATIM)
    if(K_OBJECT)
        add_library(${target} OBJECT "${base}.cpp")
    else()
        add_library(${target} STATIC "${base}.cpp")
    endif()
    target_include_directories(${target} PUBLIC "${CMAKE_CURRENT_BINARY_DIR}/generated" PRIVATE ${include_dirs})
    target_compile_definitions(${target} PRIVATE ${K_DEFINITIONS})
    target_link_libraries(${target} PUBLIC lutils::compute)
    if(TARGET lutils_development)
        target_link_libraries(${target} PRIVATE "$<BUILD_INTERFACE:lutils_development>")
    endif()
    if(kind STREQUAL "object")
        # The source declares a public C++ type. Share exactly the preprocessing
        # profile used by kernelc, including later target/dependency additions.
        target_include_directories(${target} INTERFACE "${includes}")
        target_compile_definitions(${target} INTERFACE "${definitions}")
        target_compile_options(${target} INTERFACE ${global_macros}
            "$<FILTER:${options},INCLUDE,^-D.|^-U.>")
    endif()
    set_target_properties(${target} PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
    cmake_language(EVAL CODE "cmake_language(DEFER CALL lutils_check_kernel_profile [[${target}]])")
endfunction()

function(lutils_add_kernel target)
    _lutils_add_kernel_impl(${target} function ${ARGN})
endfunction()

function(lutils_add_shader target)
    _lutils_add_kernel_impl(${target} object ${ARGN})
endfunction()
